name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Lint frontend
        run: npm run lint

      - name: Build all packages
        run: npm run build:all

      - name: Upload backend dist
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist

      - name: Upload frontend dist
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
